package com.example.withdrawal.api;

/**
 * The contract (Spec-Contract-First) for the withdrawal feature.
 *
 * <p>The implementation ({@code WithdrawalServiceImpl}) is generated by the
 * "Driver Agent" only after this contract and the accompanying tests are
 * frozen. This interface must not be modified once the contract is agreed.</p>
 */
public interface WithdrawalService {

    /**
     * Withdraws an amount from the user's account, applying the VIP fee
     * discount where applicable.
     *
     * @param request the withdrawal request (must not be {@code null})
     * @return the withdrawal result including the fee charged and new balance
     * @throws InsufficientBalanceException if the balance cannot cover the
     *                                      principal plus the fee
     */
    WithdrawResponse withdraw(WithdrawRequest request) throws InsufficientBalanceException;
}
